- name: Check if VHDX is already present
  win_stat:
    path: "{{ TEMPLATE_VHDX_DESTINATION }}"
    get_checksum: false
  register: vhdx_exists

- name: Clone Template VHDX
  win_copy:
    src: "{{ TEMPLATE_VHDX_SOURCE }}"
    dest: "{{ TEMPLATE_VHDX_DESTINATION }}"
    force: false
    remote_src: true
  when: vhdx_exists.stat.exists == false

- name: Create new Hyper V VM
  ansible.windows.win_shell: |
    New-VM -Name "{{ VM_NAME }}" -MemoryStartupBytes {{ VM_MEMORY }}GB -VHDPath "{{ TEMPLATE_VHDX_DESTINATION }}" -Generation 2 -SwitchName " {{ VM_SWITCH }}" -BootDevice VHD

- name: Start new Hyper V VM
  ansible.windows.win_shell: |
    Start-VM -Name "{{ VM_NAME }}"
  
- name: Wait for VM to be running
  local_action:
    module: wait_for
    host: "{{ TEMPLATE_IP }}"
    port: "{{ ANSIBLE_PORT }}"
    delay: 360
    state: started
  register: wait_result
