- name: Create directory for VHDX
  ansible.windows.win_file:
    path: "{{ TEMPLATE_VHDX_DESTINATION_DIR }}"
    state: directory

- name: Clone Template VHDX
  win_copy:
    src: "{{ TEMPLATE_VHDX_SOURCE }}"
    dest: "{{ TEMPLATE_VHDX_DESTINATION_DIR }}{{ VM_NAME }}.vhdx"
    remote_src: true

- name: Create new Hyper V VM
  ansible.windows.win_shell: |
    New-VM -Name "{{ VM_NAME }}" -MemoryStartupBytes "{{ VM_MEMORY }}" -VHDPath "{{ TEMPLATE_VHDX_DESTINATION }}" -Generation 2 -SwitchName " {{ VM_SWITCH }}" -BootDevice VHD

- name: Start new Hyper V VM
  ansible.windows.win_shell: |
    Start-VM -Name "{{ VM_NAME }}"
  
- name: Wait for VM to be running
  local_action:
    module: wait_for
    host: "{{ TEMPLATE_IP }}"
    port: "{{ ANSIBLE_PORT }}"
    delay: 360
    state: started
  register: wait_result
