- name: Deploy GitHub Actions Runner Container
  community.docker.docker_container:
    name: "gha-runner"
    image: "ghcr.io/binary-braids/github-actions-runner:latest@sha256:0ff48b2aef72faf13556df0bbb2fc976cbcece4675c0d142bc13a1f4cb4ecf09"
    restart_policy: always
    networks:
      - name: "proxy"
    env:
      ORGANIZATION: "{{ GH_ORG_URL }}"
      ACCESS_TOKEN: "{{ GH_ORG_TOKEN }}"
      CUSTOM_NAME: "{{ GH_CUSTOM_NAME }}"
