- name: Deploy GitHub Actions Runner Container
  community.docker.docker_container:
    name: "gha-runner"
    image: "ghcr.io/binary-braids/github-actions-runner:latest@sha256:8db8bc2d17979c39bf2c52e09009f645946773f77055439808f3b3b2daad2102"
    restart_policy: always
    networks:
      - name: "proxy"
    env:
      ORGANIZATION: "{{ GH_ORG_URL }}"
      ACCESS_TOKEN: "{{ GH_ORG_TOKEN }}"
      CUSTOM_NAME: "{{ GH_CUSTOM_NAME }}"
