parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud

trigger:
- none

stages:

- stage: 'ansibleinstall'
  dependsOn: []
  displayName: 'Ansible Install'

  jobs:
    - job: 'ansibleinstall'
      displayName: 'Ansible Install'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Ansible Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible_install.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          failOnStdErr: false