trigger:
- none

stages:

- stage: 'dockerinstall'
  dependsOn: []
  displayName: 'Docker Install'

  jobs:
    - job: 'dockerinstall'
      displayName: 'Docker Install'
      pool: Self-Hosted

      steps:
      - task: Ansible@0
        displayName: Docker Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/docker-install.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          failOnStdErr: false