- hosts: "{{ HOSTS }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - linux_template

  vars_files:
    - /ansible/vars/linux/template/linux_template_vars.yml
    - /ansible/vars/phpipam_vars.yml
