trigger:
- none

stages:

- stage: 'minecraftbedrockdocker'
  dependsOn: []
  displayName: 'Minecraft Bedrock Docker'

  jobs:
    - job: 'minecraftbedrockdocker'
      displayName: 'Oracle Management Server Setup'
      pool: Self-Hosted

      steps:
      - task: Ansible@0
        displayName: Oracle Management Server Setup
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/oracle_management_server_setup.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          failOnStdErr: false