- hosts: "{{ HOSTS }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - azure_devops_agent
    - postfix
    - oracle_vm_backup
    - oracle_terraform_keys

  vars_files:
    - /ansible/vars/linux/azure_devops_agent_vars.yml
    - /ansible/vars/linux/postfix_vars.yml
    - /ansible/vars/linux/oracle_management_server_vars.yml
    - /ansible/vars/linux/oracle_vm_backup_vars.yml
    - /ansible/vars/linux/oracle_terraform_keys_vars.yml