- hosts: "{{ HOSTS }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - azure_devops_agent
    - postfix

  vars_files:
    - /ansible/vars/linux/azure_devops_agent_vars.yml
    - /ansible/vars/linux/postfix_vars.yml
    - /ansible/vars/linux/oracle_management_server_vars.yml