- name: Install pip
  apt: 
    name: python3-pip
    state: present
    update_cache: yes

- name: Install pexpect
  pip: 
    name: pexpect
    state: present  

- name: Install AD Domain packages
  apt: 
    name: "{{ item }}"
    state: present 
    update_cache: yes
  with_items:
    - krb5-config
    - krb5-user
    - samba
    - samba-common
    - samba-dsdb-modules
    - samba-vfs-modules
    - winbind
    - libnss-winbind
    - libpam-winbind
  tags: ad

- name: Copy realmd.conf
  template: 
    src: realmd.conf.j2
    dest: /etc/realmd.conf
    owner: root
    group: root
    mode: 0644
  tags: ad

- name: Copy krb5.conf
  template: 
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  tags: ad

- name: Copy smb.conf
  template: 
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  tags: ad
  notify:
    - "samba_restart"
    - "winbind_restart"

- name: "Update nsswitch.conf"
  lineinfile:
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line   }}"
    dest: "/etc/nsswitch.conf"
  with_items:
    - { regexp: '^passwd:', line: 'passwd:		compat winbind' }
    - { regexp: '^group:' , line: 'group:		compat winbind' }
    - { regexp: '^shadow:', line: 'shadow:		compat'         }
  notify: "samba_restart"

- name: Copy pam common-session
  template: 
    src: common-session.j2
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644
  tags: ad
  
- name: "Configure home directory creation"
  lineinfile:
    dest: "/etc/pam.d/common-session"
    regexp: "pam_mkhomedir"
    line: "session optional        pam_mkhomedir.so skel=/etc/skel/ umask=0022"
  notify: "samba_restart"

- name: "Check domain status"
  command: "wbinfo --own-domain"
  register: "domain"

- name: Join system to AD
  expect:
    command:  "net join -U {{ AD_JOIN_USER }}"
    responses:
      (?i)Password: "{{ AD_JOIN_PASSWORD }}"  
  ignore_errors: yes
  become: true
  tags: ad

- name: Copy suders file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.bak

- name: Add domain admins group to sudoers
  lineinfile: dest=/etc/sudoers.tmp state=present line='%domain\ admins ALL=(ALL:ALL) ALL' regexp='^%domain'

- name: Final sudoers file check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers




