- name: Check for Existing Zabbix Installations
  ansible.builtin.command:
    zabbix_agentd -V
  register: existing_zabbix
  changed_when: false
  failed_when: false

- name: Remove Existing Zabbix Installations
  ansible.builtin.apt:
    name: zabbix-agent
    state: absent
  when: (existing_zabbix.stdout is defined) and (existing_zabbix.stdout is regex_search('zabbix_agentd')) and (existing_zabbix.stdout.split()[-1] < '6.4')

- name: Add Zabbix Repository
  ansible.builtin.apt_repository:
    repo: deb https://repo.zabbix.com/zabbix/6.4/ubuntu/ jammy main
    state: present

- name: Install Zabbix Agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: latest
    update_cache: true
  when: (existing_zabbix.stdout is not defined) or (existing_zabbix.stdout is not regex_search('zabbix_agentd')) or (existing_zabbix.stdout.split()[-1] != '6.4')

- name: Copy zabbix_agentd.conf
  ansible.builtin.template: 
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: "0644"
  notify: zabbix_restart