- name: Check installed Zabbix Agent
  ansible.builtin.shell: |
    apt list --installed 2>/dev/null | grep zabbix-agent2 | cut -d' ' -f2 | cut -d':' -f2 | cut -d'-' -f1 | cut -d'.' -f1,2
  register: zabbix_agent_check

- name: Define desired Zabbix version
  ansible.builtin.set_fact:
    desired_major_minor: '{{ zabbix_agent_version }}'

- name: Remove Existing Zabbix Installations
  ansible.builtin.apt:
    name: zabbix-agent2
    state: absent
  when: zabbix_agent_check.stdout | int < desired_major_minor and zabbix_agent_check.stdout | length > 0

- name: Add Zabbix GPG Repository Key
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/{{ desired_major_minor }}/ubuntu/dists/{{ ansible_distribution_release }}/Release.gpg
    dest: /etc/apt/keyrings/zabbix.asc

- name: Download and Install Zabbix Agent Repo - x86
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/zabbix.asc] https://repo.zabbix.com/zabbix/{{ desired_major_minor }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: ansible_architecture == "x86_64"

- name: Download and Install Zabbix Agent Repo - arm64
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/zabbix.asc] https://repo.zabbix.com/zabbix/{{ desired_major_minor }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: ansible_architecture == "aarch64"

- name: Install Zabbix Agent
  ansible.builtin.apt:
    name: zabbix-agent2
    update_cache: yes

- name: Copy zabbix_agent2.conf
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: "0644"
  notify: zabbix_restart
  when: "'kube' not in ansible_hostname"

- name: Copy zabbix_agent2.conf for K3S Nodes
  ansible.builtin.template:
    src: zabbix_agent2_k3s.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: "0644"
  notify: zabbix_restart
  when: "'kube' in ansible_hostname"

- name: Restart Zabbix agent
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
    enabled: true
