- name: Populate service facts
  ansible.builtin.service_facts:

- name: Remove Existing Zabbix Installations
  ansible.builtin.apt:
    name: zabbix-agent2
    state: absent
  when: ansible_facts.services['zabbix-agent2.service'] is defined

- name: Add Zabbix Repository
  ansible.builtin.apt:
    deb: http://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu22.04_all.deb
  when: ansible_architecture == "x86_64"

- name: Add ARM Zabbix Repository
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu-arm64/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu22.04_all.deb
  when: ansible_architecture == "aarch64"  

- name: Install Zabbix Agent
  ansible.builtin.apt:
    name: zabbix-agent2
    update_cache: true

- name: Copy zabbix_agent2.conf
  ansible.builtin.template: 
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: "0644"
  notify: zabbix_restart
  when: "'kube' not in inventory_hostname"

- name: Copy zabbix_agent2.conf for K3S Nodes
  ansible.builtin.template: 
    src: zabbix_agent2_k3s.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: "0644"
  notify: zabbix_restart
  when: "'kube' in inventory_hostname"
