- name: Populate service facts
  ansible.builtin.service_facts:

- name: Remove Existing Zabbix Installations
  ansible.builtin.apt:
    name: zabbix-agent2
    state: absent
  when: ansible_facts.services['zabbix-agent2.service'] is defined

- name: Download and Install Zabbix Agent Repo -x86
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu22.04_all.deb
  when: ansible_architecture == "x86_64"

- name: Download and Install Zabbix Agent Repo -arm64
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu-arm64/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu22.04_all.deb
  when: ansible_architecture == "aarch64"  

- name: Install zabbix-agent2
  ansible.builtin.apt:
    pkg:
    - zabbix-agent2
    - zabbix-agent2-plugin-*
    update_cache: yes

- name: Copy zabbix_agent2.conf
  ansible.builtin.template: 
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: "0644"
  notify: zabbix_restart
  when: "'kube' not in ansible_hostname"

- name: Copy zabbix_agent2.conf for K3S Nodes
  ansible.builtin.template: 
    src: zabbix_agent2_k3s.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: "0644"
  notify: zabbix_restart
  when: "'kube' in ansible_hostname"

- name: Restart Zabbix agent
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
    enabled: true