- name: Check for Existing Zabbix Installations
  command: zabbix_agentd -V
  register: existing_zabbix
  changed_when: false
  failed_when: false

- name: Get Installed Zabbix Agent Version
  set_fact:
    installed_version: "{{ ansible_pkg_mgr_facts.ansible_facts.ansible_pkg_mgr['zabbix-agent'].pkg_version }}"
  when: existing_zabbix.stdout is defined

- name: Remove Existing Zabbix Installations
  apt:
    name: zabbix-agent
    state: absent
  when: installed_version is version('6.4', '<')

- name: Add Zabbix Repository
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/6.4/ubuntu pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb"
    state: present

- name: Install Zabbix Agent
  apt:
    name: zabbix-agent
    state: latest
    update_cache: true
  when: existing_zabbix.stdout is not defined or installed_version is version('6.4', '!=')

- name: Copy zabbix_agentd.conf
  template: 
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify: zabbix_restart