- name: Check for Existing Zabbix Installations
  ansible.builtin.command:
    zabbix_agentd -V
  register: existing_zabbix
  changed_when: false
  failed_when: false

- name: Remove Existing Zabbix Installations
  ansible.builtin.apt:
    name: zabbix-agent
    state: absent
  when: "{{ existing_zabbix.stdout is defined and existing_zabbix.stdout is not regex('6.4') }}"

- name: Add Zabbix Repository
  ansible.builtin.apt:
    deb: http://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu22.04_all.deb

- name: Install Zabbix Agent
  ansible.builtin.apt:
    name: zabbix-agent2
    update_cache: true
  when: "not {{ existing_zabbix.stdout is defined and existing_zabbix.stdout is not regex('6.4') }}"

- name: Copy zabbix_agentd.conf
  ansible.builtin.template: 
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: "0644"
  notify: zabbix_restart