- name: Check installed Zabbix Agent
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding(SupportsShouldProcess)]
      param ()
    
      $ZabbixVersion = (Get-Package | Where-Object Name -match "Zabbix Agent 2").Version
      if ($ZabbixVersion) {
        $Version = [version]$ZabbixVersion
        "$($Version.Major).$($Version.Minor)"
      } else {
        "not installed"
      }
  register: zabbix_agent_check

- name: Define desired Zabbix version
  ansible.builtin.set_fact:
    desired_major_minor: '{{ zabbix_agent_version }}'

- name: Create staging location for Zabbix download
  ansible.builtin.win_file:
    path: C:\zabbix_temp
    state: directory
  when: zabbix_agent_check.output[0] | int < desired_major_minor or zabbix_agent_check.output[0] == null

- name: Download Zabbix Agent MSI
  ansible.windows.win_get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/{{ desired_major_minor }}/{{ desired_major_minor }}.0/zabbix_agent-{{ desired_major_minor }}.0-windows-amd64-openssl.msi
    dest: C:\zabbix_temp\zabbix_agent-{{ desired_major_minor }}.0-windows-amd64-openssl.msi
  register: download_result
  when: zabbix_agent_check.output[0] | int < desired_major_minor or zabbix_agent_check.output[0] == null

- name: Set Zabbix Agent MSI variable
  ansible.builtin.set_fact:
    zabbix_msi: "{{ download_result.dest.split('\\')[-1] }}"
  when: zabbix_agent_check.output[0] | int < desired_major_minor or zabbix_agent_check.output[0] == null


- name: Install Zabbix Agent
  ansible.windows.win_powershell:
    script: |
      cd C:\zabbix_temp
      msiexec /i "{{ zabbix_msi }}" /qn SERVER="{{ zabbix_server }}"
  when: zabbix_agent_check.output[0] | int < desired_major_minor or zabbix_agent_check.output[0] == null

- name: Remove staging location for Zabbix download
  ansible.builtin.win_file:
    path: C:\zabbix_temp
    state: absent
  when: zabbix_agent_check.output[0] | int < desired_major_minor or zabbix_agent_check.output[0] == null
