- name: Install Zabbix Agent for Windows
  ansible.windows.win_shell: |
    Invoke-WebRequest {{ ZABBIX_MSI }} -OutFile '{{ STAGING_LOCATION }}{{ ZABBIX_MSI }}'
    cd {{ STAGING_LOCATION }}
    msiexec /i '{{ ZABBIX_MSI }}' /qn SERVER={{ ZABBIX_SERVER }}