- name: Check installed Zabbix Agent
  ansible.windows.win_shell: |
    $ZabbixVersion = (Get-Package | Where-Object Name -match "Zabbix Agent 2").Version
    $Version = [version]$ZabbixVersion
    $($Version.Major).$($Version.Minor)
  register: zabbix_agent_check 

- name: Compare Zabbix Agent versions
  ansible.builtin.set_fact:
    upgrade_zabbix: true
  when: zabbix_agent_check is < "{{ zabbix_agent_version }}"

- name: Create staging location for Zabbix download
  ansible.builtin.win_file:
    path: C:\zabbix_temp
    state: directory
  when: upgrade_zabbix or zabbix_agent_check == null

- name: Download Zabbix Agent MSI
  ansible.windows.win_get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/{{ zabbix_agent_version }}/{{ zabbix_agent_version }}.0/zabbix_agent-{{ zabbix_agent_version }}.0-windows-amd64-openssl.msi
    dest: C:\zabbix_temp
  register: download_result
  when: upgrade_zabbix or zabbix_agent_check == null

- name: Set Zabbix Agent MSI variable
  ansible.builtin.set_fact:
    zabbix_msi: "{{ download_result.dest.split('/')[-1] }}"
  when: upgrade_zabbix or zabbix_agent_check == null

- name: Install Zabbix Agent
  ansible.windows.win_shell: |
    cd C:\zabbix_temp
    msiexec /i "{{ zabbix_msi }}" /qn SERVER="{{ zabbix_server }}"
  when: upgrade_zabbix or zabbix_agent_check == null

- name: Remove staging location for Zabbix download
  ansible.builtin.win_file:
    path: C:\zabbix_temp
    state: absent
  when: upgrade_zabbix or zabbix_agent_check == null
