- name: Check for current Zabbix Agent install
  ansible.windows.win_shell: |
    Get-WmiObject -Class Win32_Product | Select-Object Name, Version | Where-Object {$_.Name -eq "Zabbix Agent 2 (64-bit)" -And $_.Version -gt "6.4"} 
  register: zabbix_check

- name: Create staging location for Zabbix download
  ansible.builtin.win_file:
    path: C:\zabbix_temp
    state: directory
  when: zabbix_check is none or zabbix_check.stdout is empty

- name: Download Zabbix Agent MSI
  ansible.windows.win_get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/6.4/6.4.4/zabbix_agent2-6.4.4-windows-amd64-openssl.msi
    dest: C:\zabbix_temp
  register: download_result
  when: zabbix_check is none or zabbix_check.stdout is empty

- name: Set Zabbix Agent MSI variable
  ansible.builtin.set_fact:
    zabbix_msi: "{{ download_result.dest.split('/')[-1] }}"

- name: Install Zabbix Agent
  ansible.windows.win_shell: |
    cd C:\zabbix_temp
    msiexec /i "{{ zabbix_msi }}" /qn SERVER="{{ zabbix_server }}"
  when: zabbix_check is none or zabbix_check.stdout is empty

- name: Remove staging location for Zabbix download
  ansible.builtin.win_file:
    path: C:\zabbix_temp
    state: absent
  when: zabbix_check is none or zabbix_check.stdout is empty