- name: Create staging location for Zabbix download
  ansible.builtin.win_file:
    path: C:\zabbix_temp
    state: directory

- name: Download Zabbix Agent MSI
  ansible.windows.win_get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/6.4/6.4.4/zabbix_agent2-6.4.4-windows-amd64-openssl.msi
    dest: C:\zabbix_temp
  register: download_result

- name: Set Zabbix Agent MSI variable
  ansible.builtin.set_fact:
    zabbix_msi: "{{ download_result.dest.split('/')[-1] }}"

- name: Install Zabbix Agent
  ansible.windows.win_shell: |
    cd C:\zabbix_temp
    msiexec /i "{{ zabbix_msi }}" /qn SERVER="{{ zabbix_server }}"

- name: Remove staging location for Zabbix download
  ansible.builtin.win_file:
    path: C:\zabbix_temp
    state: absent