- name: deploy Portainer Container
  docker_container:
    name: "portainer"
    image: "portainer/portainer-ce:latest@sha256:4a1ceadd7f7898d9190ee0a6d22234c4323aefd80e796e84f5e57127f74370f1"
    restart_policy: always
    networks:
      - name: "proxy"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/docker/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "http"
      traefik.http.routers.portainer.rule: "Host(`{{ portainer_url }}`)"
      traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.portainer.middlewares: "portainer-https-redirect"
      traefik.http.routers.portainer-secure.entrypoints: "https"
      traefik.http.routers.portainer-secure.rule: "Host(`{{ portainer_url }}`)"
      traefik.http.routers.portainer-secure.tls: "true"
      traefik.http.routers.portainer-secure.service: "portainer"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.docker.network: "proxy"
  
