- name: deploy Portainer Container
  docker_container:
    name: "portainer"
    image: "portainer/portainer-ce:2.20.3@sha256:f5277f6cab33b3471148fb00dc4b4a09995ba64b473448a58f616d202686564b"
    restart_policy: always
    networks:
      - name: "proxy"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/docker/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "http"
      traefik.http.routers.portainer.rule: "Host(`{{ portainer_url }}`)"
      traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.portainer.middlewares: "portainer-https-redirect"
      traefik.http.routers.portainer-secure.entrypoints: "https"
      traefik.http.routers.portainer-secure.rule: "Host(`{{ portainer_url }}`)"
      traefik.http.routers.portainer-secure.tls: "true"
      traefik.http.routers.portainer-secure.service: "portainer"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.docker.network: "proxy"
  
