parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: hostSelection
  displayName: 'Ansible Host Selection'
  type: string
  default: on_prem
  values:
  - on_prem_ansible
  - oracle_management

trigger:
- none

stages:

- stage: 'adoagentinstall'
  dependsOn: []
  displayName: 'Azure DevOps Agent Install'

  jobs:
    - job: 'adoagentinstall'
      displayName: 'Azure DevOps Agent Install'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Azure DevOps Agent Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/azure_devops_agent_install.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          args: '--extra-vars "nodes=${{ parameters.hostSelection }}"'
          failOnStdErr: false