parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: hostSelection
  displayName: 'Ansible Host Selection'
  type: string
  default: on_prem_ansible
  values:
  - on_prem_ansible
  - oracle_management
- name: adoUserAndGroup
  displayName: 'Azure DevOps Agent User & Group'
  type: string
  default: ansible-admin
  values:
  - ansible-admin
  - ubuntu
- name: adoPersonalAccessToken
  displayName: 'Azure DevOps Personal Access Token'
  type: string

trigger:
- none

stages:

- stage: 'adoagentinstall'
  dependsOn: []
  displayName: 'Azure DevOps Agent Install'

  jobs:
    - job: 'adoagentinstall'
      displayName: 'Azure DevOps Agent Install'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Azure DevOps Agent Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/azure_devops_agent_install.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          args: '--extra-vars "nodes=${{ parameters.hostSelection }} ADO_AGENT_USER=${{ parameters.adoUserAndGroup }} ADO_AGENT_GROUP=${{ parameters.adoUserAndGroup }} ADO_ACCESS_TOKEN=${{ parameters.adoPersonalAccessToken }}"'
          failOnStdErr: false