parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud

trigger:
- none

stages:

- stage: 'edgeos'
  dependsOn: []
  displayName: 'Edge OS'

  jobs:
    - job: 'edgeosvpn'
      displayName: 'Edge OS Config'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Edge OS Config
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/edge_os_config.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/networking.ini'
          failOnStdErr: false