variables:
- group: ansible_linux_hosts_file_edit

parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: nodeSelection
  displayName: 'Ansible Node Selection'
  type: string
  default: on_prem
  values:
  - on_prem
  - oracle_cloud

trigger:
- none

stages:

- stage: 'linuxhostsfileedit'
  dependsOn: []
  displayName: 'Linux Hosts File Edit - ${{ parameters.nodeSelection }}'

  jobs:
    - job: 'linuxhostsfileedit'
      displayName: 'Linux Hosts File Edit - ${{ parameters.nodeSelection }}'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Linux Hosts File Edit - ${{ parameters.nodeSelection }}
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/linux_hosts_file_edit.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          args: '--extra-vars "nodes=${{ parameters.nodeSelection }} host_1=$(host_1) host_2=$(host_2) hostname_1=$(hostname_1) hostname_2=$(hostname_2) hostname_3=$(hostname_3)"'
          failOnStdErr: false