variables:
- group: ansible_linux_hosts_file_edit

parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: nodeSelection
  displayName: 'Ansible Node Selection'
  type: string
  default: on_prem
  values:
  - on_prem
  - oracle_cloud
- name: host1
  displayName: 'Host 1'
  type: string
  values: $(host_1)
- name: host2
  displayName: 'Host 2'
  type: string
  values: $(host_2)
- name: hostNames
  displayName: 'Hostnames'
  type: string
  values: $(hostnames)

trigger:
- none

stages:

- stage: 'linuxhostsfileedit'
  dependsOn: []
  displayName: 'Linux Hosts File Edit - ${{ parameters.nodeSelection }}'

  jobs:
    - job: 'linuxhostsfileedit'
      displayName: 'Linux Hosts File Edit - ${{ parameters.nodeSelection }}'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Linux Hosts File Edit - ${{ parameters.nodeSelection }}
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/linux_hosts_file_edit.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          args: '--extra-vars "nodes=${{ parameters.nodeSelection }} host_1=${{ parameters.host1 }} host_2=${{ parameters.host2 }} hostnames=${{ parameters.hostnames }}"'
          failOnStdErr: false