parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud

trigger:
- none

stages:

- stage: 'minecraftbedrockdocker'
  dependsOn: []
  displayName: 'Minecraft Bedrock Docker'

  jobs:
    - job: 'minecraftbedrockdocker'
      displayName: 'Minecraft Bedrock Docker Deployment'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Minecraft Bedrock Docker Deployment
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/minecraft_bedrock_install.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          failOnStdErr: false