parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: nodeSelection
  displayName: 'Ansible Node Selection'
  type: string
  default: oracle_docker
  values:
  - oracle_docker

trigger:
- none

stages:

- stage: 'tftpinstall'
  dependsOn: []
  displayName: 'TFTP Docker Install'

  jobs:
    - job: 'tftpinstall'
      displayName: 'TFTP Docker Install'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: TFTP Docker Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/tftp_install.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          args: '--extra-vars "nodes=${{ parameters.nodeSelection }}"'
          failOnStdErr: false
