parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud

trigger:
- none

stages:

- stage: 'windowszabbixagent'
  dependsOn: []
  displayName: 'Windows Zabbix Agent Install'

  jobs:
    - job: 'windowszabbixagent'
      displayName: 'Windows Zabbix Agent Install'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Windows Zabbix Agent Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/zabbix_windows_agent_install.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/windows.ini'
          failOnStdErr: false