variables:
- group: ansible_zabbix_linux_agent

parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: hostSelection
  displayName: 'Ansible Host Selection'
  type: string
  default: on_prem
  values:
  - on_prem
  - oracle_cloud
- name: zabbixUrl
  displayName: 'Zabbix Server URL'
  type: string
  default: $(on_prem_server_url)
  values:
    - $(on_prem_server_url)
    - $(oracle_cloud_server_url)

trigger:
- none

stages:

- stage: 'linuxzabbixagent'
  dependsOn: []
  displayName: 'Linux Zabbix Agent Install'

  jobs:
    - job: 'linuxzabbixagent'
      displayName: 'Linux Zabbix Agent Install'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Linux Zabbix Agent Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/zabbix_linux_agent_install.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/linux.ini'
          args: '--extra-vars "HOSTS=${{ parameters.hostSelection }} ZABBIX_SERVER=${{ parameters.zabbixUrl }}"'
          failOnStdErr: false