node_exporter_version: '1.8.2'
node_exporter_arch: 'amd64'
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz

node_exporter_bin_path: /usr/local/bin/node_exporter
node_exporter_collector_path: /etc/node_exporter/collector

node_exporter_options: '--collector.textfile.directory {{ node_exporter_collector_path }}'

node_exporter_state: started
node_exporter_enabled: true