- name: Check for existing OCI CLI Install
  stat:
    path: "/root/lib/oracle-cli"
  register: oci_check

- name: Install OCI CLI 
  ansible.builtin.shell: |
    bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" "" --accept-all-defaults
  when: not oci_check.stat.exists

- name: Install jq
  package:
    name: jq
    state: present

- name: Create oci_config directory
  file:
    path: "/oracle/oci/"
    state: directory

- name: Copy oci_config
  template: 
    src: oci_config.j2
    dest: "/oracle/oci/oci_config"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: 0600

- name: Copy over OCI Private Key
  ansible.builtin.copy:
    content: |
      {{ OCI_API_KEY }}
    dest: "/oracle/oci/oci_api_key.pem"
    mode: 0600

- name: Correct Private Key formatting
  ansible.builtin.shell: |
    echo -ne $(cat /oracle/oci/oci_api_key.pem) > /oracle/oci/oci_api_key.pem

- name: Create backup script directory
  file:
    path: "/oracle/oracle_vm_backup/"
    state: directory

- name: Copy over backup script
  template: 
    src: backup_script.sh.j2
    dest: "/oracle/oracle_vm_backup/{{ item }}-backup.sh"
    mode: u+x
  loop: "{{ BACKUP_NAME }}"

- name: Setup backup script cronjobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    job: "{{ item.job }}"
  loop: "{{ BACKUP_CRON_SETTINGS }}"