- name: deploy TFTP Network
  docker_network:
    name: "tftpd-hpa"

- name: deploy TFTP Container
  docker_container:
    name: "tftpd-hpa"
    image: "3x3cut0r/tftpd-hpa:latest@sha256:5f03043292a3ffbd9a777da417501a11363910af27936f950a3593929cb0e098"
    restart_policy: always
    networks:
      - name: "tftpd-hpa"
    published_ports:
      - "69:69"
    volumes:
      - "/var/lib/docker/tftpd-hpa:/tftpboot"
