- name: deploy TFTP Network
  docker_network:
    name: "tftpd-hpa"

- name: deploy TFTP Container
  docker_container:
    name: "tftpd-hpa"
    image: "3x3cut0r/tftpd-hpa:latest@sha256:c389bb37bfd3291f53627db85884622f20c23bf8835f621f3e26a1ebb3728439"
    restart_policy: always
    networks:
      - name: "tftpd-hpa"
    published_ports:
      - "69:69"
    volumes:
      - "/var/lib/docker/tftpd-hpa:/tftpboot"
