- name: deploy TFTP Network
  docker_network:
    name: "tftpd-hpa"

- name: deploy TFTP Container
  docker_container:
    name: "tftpd-hpa"
    image: "3x3cut0r/tftpd-hpa:latest@sha256:37eeb2b2584889019a3d9a8254ec25f14b4c1356ddaea25cfa5a9fec7493e05c"
    restart_policy: always
    networks:
      - name: "tftpd-hpa"
    published_ports:
      - "69:69"
    volumes:
      - "/var/lib/docker/tftpd-hpa:/tftpboot"
