- name: deploy Minecraft Bedrock container network
  docker_network:
    name: "minecraft-bedrock"

- name: deploy Minecraft Docker Container
  docker_container:
    name: "minecraft-bedrock"
    image: "itzg/minecraft-bedrock-server"
    restart_policy: always
    networks:
      - name: "minecraft-bedrock"
    ports:
      - "19132:19132/udp"
    env:
      EULA: "true"
      SERVER_NAME: "{{ SERVER_NAME }}"
      GAMEMODE: "{{ GAME_MODE }}"
      DIFFICULTY: "{{ DIFFICULTY }}"
      ONLINE_MODE: "{{ ONLINE_MODE }}"
    volumes:
      - "{{ VOLUME }}"


    
    