- name: Configure IPSec VPN to Oracle Cloud
  community.network.edgeos_config:
    lines:
    -  set vpn ipsec ike-group "{{ IKE_GROUP_1 }}" key-exchange ikev1 
    -  set vpn ipsec ike-group "{{ IKE_GROUP_1 }}" lifetime 28800 
    -  set vpn ipsec ike-group "{{ IKE_GROUP_1 }}" proposal 1 dh-group 20 
    -  set vpn ipsec ike-group "{{ IKE_GROUP_1 }}" proposal 1 encryption aes256 
    -  set vpn ipsec ike-group "{{ IKE_GROUP_1 }}" proposal 1 hash sha256
    -  set vpn ipsec esp-group "{{ ESP_GROUP_1 }}" lifetime 3600 
    -  set vpn ipsec esp-group "{{ ESP_GROUP_1 }}" pfs enable 
    -  set vpn ipsec esp-group "{{ ESP_GROUP_1 }}" proposal 1 encryption aes256 
    -  set vpn ipsec esp-group "{{ ESP_GROUP_1 }}" proposal 1 hash sha256
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_1 }}" authentication mode pre-shared-secret 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_1 }}" authentication pre-shared-secret "{{ IPSEC_PSK_1 }}"
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_1 }}" description "{{ IPSEC_DESCRIPTION_1 }}" 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_1 }}" local-address "{{ LOCAL_WAN_IP }}" 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_1 }}" ike-group "{{ IKE_GROUP_1 }}" 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_1 }}" vti bind "{{ VTI_INTERFACE_1 }}" 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_1 }}" vti esp-group "{{ ESP_GROUP_1 }}"
    -  set interfaces vti "{{ VTI_INTERFACE_1 }}"
    -  set firewall options mss-clamp interface-type vti 
    -  set firewall options mss-clamp mss 1350   
    -  set protocols static interface-route "{{ REMOTE_PEER_LAN }}" next-hop-interface "{{ VTI_INTERFACE_1 }}"
    -  set vpn ipsec ike-group "{{ IKE_GROUP_2 }}" key-exchange ikev1 
    -  set vpn ipsec ike-group "{{ IKE_GROUP_2 }}" lifetime 28800 
    -  set vpn ipsec ike-group "{{ IKE_GROUP_2 }}" proposal 1 dh-group 20 
    -  set vpn ipsec ike-group "{{ IKE_GROUP_2 }}" proposal 1 encryption aes256 
    -  set vpn ipsec ike-group "{{ IKE_GROUP_2 }}" proposal 1 hash sha256
    -  set vpn ipsec esp-group "{{ ESP_GROUP_2 }}" lifetime 3600 
    -  set vpn ipsec esp-group "{{ ESP_GROUP_2 }}" pfs enable 
    -  set vpn ipsec esp-group "{{ ESP_GROUP_2 }}" proposal 1 encryption aes256 
    -  set vpn ipsec esp-group "{{ ESP_GROUP_2 }}" proposal 1 hash sha256
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_2 }}" authentication mode pre-shared-secret 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_2 }}" authentication pre-shared-secret "{{ IPSEC_PSK_2 }}"
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_2 }}" description "{{ IPSEC_DESCRIPTION_2 }}" 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_2 }}" local-address "{{ LOCAL_WAN_IP }}" 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_2 }}" ike-group "{{ IKE_GROUP_2 }}" 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_2 }}" vti bind "{{ VTI_INTERFACE_2 }}" 
    -  set vpn ipsec site-to-site peer "{{ REMOTE_PEER_2 }}" vti esp-group "{{ ESP_GROUP_2 }}"
    -  set interfaces vti "{{ VTI_INTERFACE_2 }}"
    -  set firewall options mss-clamp interface-type vti 
    -  set firewall options mss-clamp mss 1350   
    -  set protocols static interface-route "{{ REMOTE_PEER_LAN }}" next-hop-interface "{{ VTI_INTERFACE_2 }}"