- name: deploy Monica Container Network 
  docker_network:
    name: "monica"

- name: deploy Monica DB Docker Container
  docker_container:
    name: "monica-db"
    image: "mysql:9.0@sha256:86cdfe832c81e39a89cfb63c3fde1683c41cc00ef91e67653c9c1df0ba80f454"
    restart_policy: always
    networks:
      - name: "monica"
    env:
      MYSQL_DATABASE: "monica"
      MYSQL_USER: "monica"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - "{{ MYSQL_VOLUME }}"

- name: deploy Monica Docker Container
  docker_container:
    name: "monica"
    image: "monica:apache@sha256:fc47cf76bc68bee0987eb9bf3abf3e0008cefe804a9873ef8a71f965c6c12285"
    restart_policy: always
    networks:
      - name: "monica"
    ports:
      - "8081:80"
    env:
      DB_HOST: "monica-db"
      DB_USERNAME: "monica"
      DB_PASSWORD: "{{ MYSQL_PASSWORD }}"
      APP_DISABLE_SIGNUP: "false"
    volumes:
      - "{{ MONICA_VOLUME }}"


    
    