- name: deploy Monica Container Network 
  docker_network:
    name: "monica"

- name: deploy Monica DB Docker Container
  docker_container:
    name: "monica-db"
    image: "mysql:8.4@sha256:a13510e6c70e4be896cb904ba1fe3d4d466193928324744bb2356e865c097ebb"
    restart_policy: always
    networks:
      - name: "monica"
    env:
      MYSQL_DATABASE: "monica"
      MYSQL_USER: "monica"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - "{{ MYSQL_VOLUME }}"

- name: deploy Monica Docker Container
  docker_container:
    name: "monica"
    image: "monica:apache@sha256:1c2696e3edb6a209bdd0fec920e9dd6b74f8707d778c084bf28d4ce9df005ed7"
    restart_policy: always
    networks:
      - name: "monica"
    ports:
      - "8081:80"
    env:
      DB_HOST: "monica-db"
      DB_USERNAME: "monica"
      DB_PASSWORD: "{{ MYSQL_PASSWORD }}"
      APP_DISABLE_SIGNUP: "false"
    volumes:
      - "{{ MONICA_VOLUME }}"


    
    