- name: deploy Monica Container Network 
  docker_network:
    name: "monica"

- name: deploy Monica DB Docker Container
  docker_container:
    name: "monica-db"
    image: "mysql:8.4@sha256:dab7049abafe3a0e12cbe5e49050cf149881c0cd9665c289e5808b9dad39c9e0"
    restart_policy: always
    networks:
      - name: "monica"
    env:
      MYSQL_DATABASE: "monica"
      MYSQL_USER: "monica"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - "{{ MYSQL_VOLUME }}"

- name: deploy Monica Docker Container
  docker_container:
    name: "monica"
    image: "monica:apache@sha256:daf27f283dace79bf578af6f858325c983acd04538df920683dd42522c492f34"
    restart_policy: always
    networks:
      - name: "monica"
    ports:
      - "8081:80"
    env:
      DB_HOST: "monica-db"
      DB_USERNAME: "monica"
      DB_PASSWORD: "{{ MYSQL_PASSWORD }}"
      APP_DISABLE_SIGNUP: "false"
    volumes:
      - "{{ MONICA_VOLUME }}"


    
    