- name: deploy Monica Container Network 
  docker_network:
    name: "monica"

- name: deploy Monica DB Docker Container
  docker_container:
    name: "monica-db"
    image: "mysql:9.0@sha256:c69299937e5e2fc9a2cb26f5cd7a7151e48d9d5a3b3679f62bfd1275de698c0c"
    restart_policy: always
    networks:
      - name: "monica"
    env:
      MYSQL_DATABASE: "monica"
      MYSQL_USER: "monica"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - "{{ MYSQL_VOLUME }}"

- name: deploy Monica Docker Container
  docker_container:
    name: "monica"
    image: "monica:apache@sha256:760af03323f1aee8b2dbcd3ec4fbaf8887816d24ef0d28fa2334dd572bf04fd7"
    restart_policy: always
    networks:
      - name: "monica"
    ports:
      - "8081:80"
    env:
      DB_HOST: "monica-db"
      DB_USERNAME: "monica"
      DB_PASSWORD: "{{ MYSQL_PASSWORD }}"
      APP_DISABLE_SIGNUP: "false"
    volumes:
      - "{{ MONICA_VOLUME }}"


    
    