- name: Create VeeamScripts directory
  ansible.windows.win_file:
    path: C:\VeeamScripts
    state: directory

- name: Download VeeamNotify
  ansible.windows.win_get_url:
    url: https://github.com/tigattack/VeeamNotify/releases/download/v1.0.1/VeeamNotify-v1.0.1.zip
    dest: C:\VeeamScripts\VeeamNotify-v1.0.1.zip

- name: Extract VeeamNotify
  community.windows.win_unzip:
    src: C:\VeeamScripts\VeeamNotify-v1.0.1.zip
    dest: C:\VeeamScripts
    delete_archive: yes

- name: Copy conf.json file
  ansible.windows.win_template:
    src: conf.json.j2
    dest: C:\VeeamScripts\VeeamNotify-v1.0.1\config\conf.json

- name: Configure Veeam Jobs with notification script
  ansible.windows.win_powershell: |
    $veeamNotifierScript = "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -File 'C:\VeeamScripts\VeeamNotify-v1.0.1\Bootstrap.ps1'"

    Write-Host "Gathering list of jobs"
    $jobList = Get-VBRJob

    foreach ($job in $jobList) {
        Write-Host "---------------------------------------------------------"
        Write-Host "Setting Post Script configuration on job: $($job.Name)..."

        if ($job.JobType -eq "SimpleBackupCopyPolicy") {
            $job = Get-VBRBackupCopyJob -Name $job.Name
            $scriptOptions = New-VBRJobScriptOptions -PostScriptEnabled -PostCommand "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -File 'C:\VeeamScripts\VeeamNotify-v1.0.1\Bootstrap.ps1'" -Periodicity Cycles -Frequency 1
            Set-VBRBackupCopyJob -Job $job -ScriptOptions $scriptOptions | Out-Null 
            Enable-VBRBackupCopyJob -Job $job
        }
        else {
            $job = Get-VBRJob | Where-Object {$_.Name -eq $job.Name}
            $jobOptions = Get-VBRJobOptions $job
            $jobOptions.JobScriptCommand.PostScriptEnabled = $true
            $jobOptions.JobScriptCommand.PostScriptCommandLine = $veeamNotifierScript
            Set-VBRJobOptions $job $jobOptions | Out-Null 
        }    
        
        Write-Host "Post Script configuration was successfully applied on job: $($job.Name)"
        Write-Host "---------------------------------------------------------"    
    }

