- name: deploy Mealie Container Network 
  docker_network:
    name: "mealie"

- name: deploy Mealie Docker Container
  docker_container:
    name: "mealie"
    image: "hkotel/mealie:latest@sha256:7f776bbb5457db7f58951c11e3aa881f0167675a78459d7a7f2cd5e42d181fa5"
    restart_policy: always
    networks:
      - name: "mealie"
    published_ports: 
      - "9090:80"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Africa/Johannesburg"

      # Default Recipe Settings
      RECIPE_PUBLIC: "true"
      RECIPE_SHOW_NUTRITION: "true"
      RECIPE_SHOW_ASSETS: "true"
      RECIPE_LANDSCAPE_VIEW: "true"
      RECIPE_DISABLE_COMMENTS: "false"
      RECIPE_DISABLE_AMOUNT: "false"

      # Gunicorn
      WEB_CONCURRENCY: "1"
      WORKERS_PER_CORE: "0.5"
      MAX_WORKERS: "1"
    volumes:
      - "{{ MEALIE_VOLUME }}"

