- hosts: "{{ nodes }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - ../roles/docker_minecraft_bedrock

  vars_files:
    - /ansible/vars/docker/minecraft_bedrock/minecraft_bedrock_vars.yml