- hosts: "{{ HOSTS }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - ../roles/zabbix_linux_agent

  vars_files:
    - /ansible/vars/windows/zabbix_agent/zabbix_linux_agent_vars.yml