- name: deploy Zabbix Container Network 
  docker_network:
    name: "zabbix"

- name: deploy Zabbix Mysql Docker Container
  docker_container:
    name: "zabbix-db"
    image: "mysql@sha256:8b879a3959bc59adcb7281a41950d39cf8c9b3fb23b87b9b62318ce884a7c383"
    restart_policy: always
    networks:
      - name: "zabbix"
    env:
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
    volumes:
     - "{{ MYSQL_VOLUME }}" 


- name: deploy Zabbix Server Docker Container
  docker_container:
    name: "zabbix-server"
    image: "zabbix/zabbix-server-mysql:alpine-6.2-latest@sha256:854547f7b044c028aa7ff8ec9a96ad01e8b192ccc9b56f16c35eb13c57ca67f2"
    restart_policy: always
    networks:
      - name: "zabbix"
    published_ports: 
      - "10051:10051"
    env:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix-db"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"

- name: deploy Zabbix Web Server Docker Container
  docker_container:
    name: "zabbix-web-server"
    image: "zabbix/zabbix-web-apache-mysql:alpine-6.2-latest@sha256:816ba9d3916933fd3a7dfeeae802fba55826574cb5917af1eec87032d8d8d877"
    restart_policy: always
    networks:
      - name: "zabbix"
    published_ports: 
      - "8090:8080"
    env:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix-db"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"  
      PHP_TZ: "Africa/Johannesburg"   

