- name: Ensure Image directory exists
  file: 
    path: "/docker/images"
    state: directory

- name: Copy Dockerfile
  template: 
    src: azp_agent_linux.dockerfile.j2
    dest: /docker/images/azp_agent
    owner: root
    group: root
    mode: 0644

- name: Copy start.sh
  template: 
    src: start.sh.j2
    dest: /docker/images/azp_agent
    owner: root
    group: root
    mode: 0644

- name: Build Azure DevOps Agent Container
  community.docker.docker_image:
    name: ado-agent:linux
    build:
      path: /docker/images/azp_agent
    source: build

- name: Deploy Azure Pipelines Docker Container
  docker_container:
    name: "ado-agent"
    image: "ado-agent:linux"
    restart_policy: always
    networks:
      - name: "proxy"
    env:
      AZP_URL: "{{ AZP_URL }}"
      AZP_TOKEN: "{{ AZP_TOKEN }}"
      AZP_POOL: "{{ AZP_POOL }}"
      AZP_AGENT_NAME: "{{ AZP_AGENT_NAME }}"