- name: deploy phpipam Container Network 
  docker_network:
    name: "phpipam"

- name: deploy phpipam DB Docker Container
  docker_container:
    name: "phpipam-db"
    image: "mysql:9.0@sha256:c69299937e5e2fc9a2cb26f5cd7a7151e48d9d5a3b3679f62bfd1275de698c0c"
    restart_policy: always
    networks:
      - name: "phpipam"
    env:
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
    volumes:
      - "{{ PHPIPAM_DB_VOLUME }}"

- name: deploy phpipam Docker Container
  docker_container:
    depends_on: "phpipam-db"
    name: "phpipam"
    image: "pierrecdn/phpipam@sha256:3267dba3072079446cf612fbbe7cb4d632389fc23bd9f4fbba45c095bf25be5e"
    restart_policy: always
    networks:
      - name: "phpipam"
    env:
      MYSQL_ENV_MYSQL_USER: "root"
      MYSQL_ENV_MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
      MYSQL_ENV_MYSQL_HOST: "phpipam-db"
    ports:
      - "81:80"
    volumes:
      - "{{ PHPIPAM_VOLUME }}"


    
    