- name: deploy phpipam Container Network 
  docker_network:
    name: "phpipam"

- name: deploy phpipam DB Docker Container
  docker_container:
    name: "phpipam-db"
    image: "mysql:8.4@sha256:a13510e6c70e4be896cb904ba1fe3d4d466193928324744bb2356e865c097ebb"
    restart_policy: always
    networks:
      - name: "phpipam"
    env:
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
    volumes:
      - "{{ PHPIPAM_DB_VOLUME }}"

- name: deploy phpipam Docker Container
  docker_container:
    depends_on: "phpipam-db"
    name: "phpipam"
    image: "pierrecdn/phpipam@sha256:3267dba3072079446cf612fbbe7cb4d632389fc23bd9f4fbba45c095bf25be5e"
    restart_policy: always
    networks:
      - name: "phpipam"
    env:
      MYSQL_ENV_MYSQL_USER: "root"
      MYSQL_ENV_MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
      MYSQL_ENV_MYSQL_HOST: "phpipam-db"
    ports:
      - "81:80"
    volumes:
      - "{{ PHPIPAM_VOLUME }}"


    
    